// apps/ui/src/components/EventRow.vue
<script setup lang="ts">
import { computed } from 'vue';
import { useRouter } from 'vue-router';
import StationIcon from './StationIcon.vue';
import type { HistoryEntry } from '../lib/types';

const props = defineProps<{ entry: HistoryEntry }>();
const router = useRouter();
const MAX_BODY = 140;

const text = computed(() => {
  const b = props.entry.text ?? (props.entry.emoji ? `[react ${props.entry.emoji}]` : '(no text)');
  return b.length > MAX_BODY ? b.slice(0, MAX_BODY - 1) + '…' : b;
});
const sender = computed(() => (props.entry.fromName ?? props.entry.from).replace(/^metro:\/\//, ''));
const lineLabel = computed(() => props.entry.lineName ?? props.entry.line.replace(/^metro:\/\//, ''));
const ts = computed(() => {
  try { return new Date(props.entry.ts).toLocaleTimeString([], { hour12: false }); }
  catch { return props.entry.ts.slice(11, 19); }
});
const kindColor = computed(() =>
  props.entry.kind === 'inbound' ? 'text-metro-accent'
    : props.entry.kind === 'outbound' ? 'text-metro-ok'
      : 'text-metro-warn',
);

function open(): void {
  void router.push({
    name: 'event', params: { id: props.entry.id },
    query: { data: JSON.stringify(props.entry) },
  });
}
</script>

<template>
  <button
    type="button"
    class="w-full text-left px-4 py-3 border-b border-metro-border-light dark:border-metro-border-dark
      bg-metro-surface-light dark:bg-metro-surface-dark hover:bg-metro-hover-light dark:hover:bg-metro-hover-dark transition-colors"
    @click="open"
  >
    <div class="flex items-center gap-2 mb-1">
      <StationIcon :station="entry.station" />
      <span class="text-[11px] font-semibold uppercase" :class="kindColor">{{ entry.kind }}</span>
      <span class="text-xs text-metro-sub-light dark:text-metro-sub-dark truncate flex-1">{{ sender }}</span>
      <span class="text-xs text-metro-sub-light dark:text-metro-sub-dark">{{ ts }}</span>
    </div>
    <div class="text-xs text-metro-sub-light dark:text-metro-sub-dark truncate">{{ lineLabel }}</div>
    <div class="text-sm text-metro-fg-light dark:text-metro-fg-dark whitespace-pre-wrap line-clamp-3">{{ text }}</div>
  </button>
</template>

// apps/app/components/EventRow.tsx
import { Pressable, Text, View, useColorScheme } from 'react-native';
import { StationIcon } from './StationIcon';
import type { HistoryEntry } from '../lib/types';

const MAX_BODY = 140;

function fmtTs(ts: string): string {
  /** ISO timestamp → HH:MM:SS, in local time (Date does the conversion). */
  try { return new Date(ts).toLocaleTimeString([], { hour12: false }); }
  catch { return ts.slice(11, 19); }
}

export function EventRow({ entry, onPress, unread = false }: {
  entry: HistoryEntry; onPress: () => void; unread?: boolean;
}): React.ReactElement {
  const dark = useColorScheme() === 'dark';
  const sub = dark ? '#8a94a6' : '#5a6477';
  const body = entry.text ?? (entry.emoji ? `[react ${entry.emoji}]` : '(no text)');
  const trunc = body.length > MAX_BODY ? body.slice(0, MAX_BODY - 1) + '…' : body;
  const kindColor = entry.kind === 'inbound' ? '#5aa9ff' : entry.kind === 'outbound' ? '#83c989' : '#c0a06e';
  const sender = (entry.fromName ?? entry.from).replace(/^metro:\/\//, '');

  return (
    <Pressable
      onPress={onPress}
      style={({ pressed }) => ({
        backgroundColor: pressed ? (dark ? '#1d2230' : '#eef1f7') : (dark ? '#161a22' : '#fafbfd'),
        paddingHorizontal: 14, paddingVertical: 10,
        borderBottomWidth: 1, borderBottomColor: dark ? '#262c38' : '#e3e7ef',
        borderLeftWidth: unread ? 3 : 0,
        borderLeftColor: unread ? '#ffffff' : 'transparent',
      })}
    >
      <View style={{ flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 4 }}>
        <StationIcon station={entry.station} />
        <Text style={{ fontSize: 11, fontWeight: '600', color: kindColor }}>{entry.kind}</Text>
        <Text style={{ fontSize: 11, color: sub, flex: 1 }} numberOfLines={1}>{sender}</Text>
        <Text style={{ fontSize: 11, color: sub }}>{fmtTs(entry.ts)}</Text>
      </View>
      <Text style={{ fontSize: 11, color: sub, marginBottom: 2 }} numberOfLines={1}>
        {entry.lineName ?? entry.line.replace(/^metro:\/\//, '')}
      </Text>
      <Text style={{ fontSize: 14, color: dark ? '#e8ecf2' : '#1a1f29' }} numberOfLines={3}>
        {trunc}
      </Text>
    </Pressable>
  );
}
