// apps/ui/src/components/MessengerBubble.vue
<script setup lang="ts">
/** ChatGPT-dark-inspired bubble with inline attachment rendering. */
import { parseRichText } from '../lib/rich-text';
import type { HistoryEntry } from '../lib/types';

interface Attachment { id: string; url: string; kind: string; mime: string; size: number; name?: string }

const props = defineProps<{ entry: HistoryEntry; daemonUrl: string; token: string }>();

const MESSENGER_USER = 'metro://messenger/user/owner';
const mine = computed(() => props.entry.from === MESSENGER_USER);
const attachments = computed<Attachment[]>(() => {
  const p = props.entry.payload as { attachments?: Attachment[] } | undefined;
  return Array.isArray(p?.attachments) ? p!.attachments : [];
});
const parts = computed(() => props.entry.text ? parseRichText(props.entry.text) : []);

function fullUrl(att: Attachment): string {
  return `${props.daemonUrl.replace(/\/$/, '')}${att.url}?token=${encodeURIComponent(props.token)}`;
}

function fmtTs(ts: string): string {
  try { return new Date(ts).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', hour12: false }); }
  catch { return ts.slice(11, 16); }
}

function fmtSize(n: number): string {
  if (n < 1024) return `${n} B`;
  if (n < 1024 * 1024) return `${(n / 1024).toFixed(0)} KB`;
  return `${(n / 1024 / 1024).toFixed(1)} MB`;
}
</script>

<template>
  <div class="flex" :class="mine ? 'justify-end' : 'justify-start'">
    <div
      class="max-w-[78%] px-3.5 py-2 leading-snug text-[15px] rounded-2xl flex flex-col gap-1.5"
      :class="mine
        ? 'bg-metro-fg-light dark:bg-white text-white dark:text-black rounded-br-md'
        : 'bg-metro-hover-light dark:bg-[#2a2d33] text-metro-fg-light dark:text-metro-fg-dark rounded-bl-md'"
    >
      <template v-for="att in attachments" :key="att.id">
        <img
          v-if="att.kind === 'image'"
          :src="fullUrl(att)"
          class="max-w-full max-h-[280px] rounded-lg object-cover"
          loading="lazy"
        />
        <audio
          v-else-if="att.kind === 'audio'"
          :src="fullUrl(att)"
          controls
          class="w-[260px] max-w-full"
        />
        <video
          v-else-if="att.kind === 'video'"
          :src="fullUrl(att)"
          controls
          class="max-w-full max-h-[280px] rounded-lg"
        />
        <a
          v-else
          :href="fullUrl(att)"
          target="_blank"
          rel="noopener"
          class="flex items-center gap-2 px-2 py-1.5 rounded-md bg-black/10 dark:bg-white/10 text-current no-underline"
        >
          <span>📎</span>
          <span class="flex-1 truncate text-[13px]">{{ att.name ?? att.id }}</span>
          <span class="text-[11px] opacity-60">{{ fmtSize(att.size) }}</span>
        </a>
      </template>
      <div v-if="parts.length" class="select-text break-words whitespace-pre-wrap">
        <template v-for="(p, i) in parts" :key="i">
          <a
            v-if="p.kind === 'link'"
            :href="p.href"
            target="_blank"
            rel="noopener"
            class="underline text-current"
          >{{ p.label }}</a>
          <template v-else>{{ p.value }}</template>
        </template>
      </div>
      <div
        class="text-[10px] opacity-60"
        :class="mine ? 'text-right' : 'text-left'"
      >{{ fmtTs(entry.ts) }}</div>
    </div>
  </div>
</template>

// apps/app/components/MessengerBubble.tsx
/** ChatGPT-dark-style chat bubble — right for owner, left for everyone else. */

import { Image, Linking, Pressable, Text, View } from 'react-native';
import { parseRichText } from '../lib/rich-text';
import type { HistoryEntry } from '../lib/types';

const MESSENGER_USER = 'metro://messenger/user/owner';

interface Attachment { id: string; url: string; kind: string; mime: string; size: number; name?: string }

function fmtTs(ts: string): string {
  try { return new Date(ts).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', hour12: false }); }
  catch { return ts.slice(11, 16); }
}

function attachmentsOf(entry: HistoryEntry): Attachment[] {
  const p = entry.payload as { attachments?: Attachment[] } | undefined;
  return Array.isArray(p?.attachments) ? p.attachments : [];
}

function AttachmentView({ att, fullUrl, fg }: {
  att: Attachment; fullUrl: string; fg: string;
}): React.ReactElement {
  if (att.kind === 'image') {
    return (
      <Image
        source={{ uri: fullUrl }}
        style={{ width: 220, height: 220, borderRadius: 10, marginBottom: 6 }}
        resizeMode="cover"
      />
    );
  }
  const icon = att.kind === 'audio' ? '🎤' : '📎';
  const label = att.name ?? `${att.kind} attachment`;
  return (
    <Pressable
      onPress={() => void Linking.openURL(fullUrl)}
      style={{
        flexDirection: 'row', alignItems: 'center', gap: 8,
        paddingHorizontal: 10, paddingVertical: 6, borderRadius: 8,
        backgroundColor: 'rgba(0,0,0,0.12)', marginBottom: 6,
      }}
    >
      <Text style={{ color: fg, fontSize: 14 }}>{icon}</Text>
      <Text style={{ color: fg, fontSize: 13, flexShrink: 1 }} numberOfLines={1}>{label}</Text>
    </Pressable>
  );
}

export function MessengerBubble({ entry, dark, unread, onPress, daemonUrl, token }: {
  entry: HistoryEntry; dark: boolean; unread: boolean; onPress: () => void;
  daemonUrl: string; token: string;
}): React.ReactElement {
  const mine = entry.from === MESSENGER_USER;
  const bg = mine ? (dark ? '#ffffff' : '#1a1f29') : (dark ? '#2a2d33' : '#eef1f7');
  const fg = mine ? (dark ? '#000000' : '#ffffff') : (dark ? '#e8ecf2' : '#1a1f29');
  const atts = attachmentsOf(entry);
  return (
    <View style={{
      flexDirection: 'row',
      justifyContent: mine ? 'flex-end' : 'flex-start',
      paddingHorizontal: 12, paddingVertical: 3,
    }}>
      <Pressable
        onPress={onPress}
        style={({ pressed }) => ({
          maxWidth: '78%',
          backgroundColor: bg,
          opacity: pressed ? 0.85 : 1,
          paddingHorizontal: 14, paddingVertical: 9,
          borderTopLeftRadius: 20, borderTopRightRadius: 20,
          borderBottomLeftRadius: mine ? 20 : 6,
          borderBottomRightRadius: mine ? 6 : 20,
          borderWidth: unread ? 1.5 : 0,
          borderColor: unread ? (dark ? '#ffffff' : '#1a1f29') : 'transparent',
        })}
      >
        {atts.map(a => (
          <AttachmentView
            key={a.id}
            att={a}
            fg={fg}
            fullUrl={`${daemonUrl.replace(/\/$/, '')}${a.url}?token=${encodeURIComponent(token)}`}
          />
        ))}
        {entry.text ? (
          <Text selectable style={{ color: fg, fontSize: 15, lineHeight: 20 }}>
            {parseRichText(entry.text).map((p, i) => p.kind === 'link' ? (
              <Text
                key={i}
                style={{ textDecorationLine: 'underline' }}
                onPress={() => void Linking.openURL(p.href)}
              >{p.label}</Text>
            ) : <Text key={i}>{p.value}</Text>)}
          </Text>
        ) : null}
        <Text style={{
          color: fg, opacity: 0.55, fontSize: 10, marginTop: 3,
          textAlign: mine ? 'right' : 'left',
        }}>{fmtTs(entry.ts)}</Text>
      </Pressable>
    </View>
  );
}
